const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const dom = new JSDOM(fs.readFileSync(0, 'utf8'), {runScripts: 'outside-only', url: 'https://example.org'});
const w = dom.window;
w.fetch = async () => ({ok: true});
w.eval(fs.readFileSync('static/admin_floorplan.js', 'utf8'));
w.eval(fs.readFileSync('static/admin_inventory.js', 'utf8'));
const id = name => w.document.getElementById(name);
const button = number => w.document.querySelector(`.picker-btn[data-number="${number}"]`);
const tick = () => new Promise(resolve => setTimeout(resolve, 0));
(async () => {
  id('plan-table-search').value = '20';
  id('plan-table-search').dispatchEvent(new w.Event('input'));
  assert.equal(button(20).hidden, false);
  assert.equal(button(1).hidden, true);
  id('plan-table-search').value = '';
  id('plan-placement-filter').value = 'unplaced';
  id('plan-placement-filter').dispatchEvent(new w.Event('change'));
  assert.equal(button(1).hidden, true);
  assert.equal(button(2).hidden, false);
  button(2).click();
  assert.equal(button(2).getAttribute('aria-pressed'), 'true');
  id('plan-image').getBoundingClientRect = () => ({left:0,top:0,width:100,height:100});
  id('plan-image').dispatchEvent(new w.MouseEvent('click', {clientX:30,clientY:40}));
  await tick();
  assert.equal(button(2).hidden, true);
  const marker = w.document.querySelector('.plan-marker[data-number="2"]');
  assert.equal(marker.getAttribute('role'), 'button');
  marker.dispatchEvent(new w.KeyboardEvent('keydown', {key:'Enter',bubbles:true}));
  assert.match(id('picker-status').textContent, /Tisch 2 ausgewählt/);
  id('plan-table-search').value = '999';
  id('plan-table-search').dispatchEvent(new w.Event('input'));
  assert.equal(id('plan-picker-empty').hidden, false);
  dom.window.close();
  console.log('Inventory search, placement filters, save updates and keyboard selection passed.');
})().catch(error => { console.error(error); dom.window.close(); process.exitCode = 1; });
